<x-guest-layout title="Richiedi giacenza"><h1>Richiedi giacenza</h1><p class="my-4 break-words font-semibold">{{ $item->name }}</p><p class="mb-5 text-sm text-slate-600">{{ $item->retailer->company_name }} · La richiesta non prenota il prodotto e non costituisce un acquisto.</p>
@if(session('status'))<x-alert variant="success">{{ session('status') }}</x-alert>@endif
<form method="POST" action="{{ route('availability.store',$item) }}" class="mt-5 space-y-5">@csrf
<x-field name="customer_name" label="Nome" required autocomplete="name" /><x-field name="customer_company" label="Azienda" autocomplete="organization" /><x-field name="customer_email" label="Email" type="email" required autocomplete="email" /><x-field name="customer_phone" label="Telefono" type="tel" autocomplete="tel" /><x-field name="quantity" label="Quantità richiesta" inputmode="decimal" required hint="Fino a tre decimali. La disponibilità sarà verificata dal rivenditore." />
<x-textarea name="message" label="Messaggio" rows="4" maxlength="5000">{{ old('message') }}</x-textarea>
<div aria-hidden="true" class="hidden"><label for="contact_website">Lascia vuoto questo campo</label><input name="contact_website" id="contact_website" tabindex="-1" autocomplete="off"></div>
<label for="privacy_consent" class="flex min-h-11 items-start gap-3"><input id="privacy_consent" class="mt-1" type="checkbox" @if($errors->has('privacy_consent')) aria-invalid="true" aria-describedby="privacy_consent-error" @endif name="privacy_consent" value="1" required @checked(old('privacy_consent'))><span class="text-sm">Ho letto <a class="font-semibold underline" href="{{ config('availability.privacy_url') ?: route('privacy') }}" target="_blank" rel="noopener noreferrer">l’informativa privacy</a> e acconsento all’invio dei dati al rivenditore per gestire questa richiesta.</span></label>@error('privacy_consent')<p id="privacy_consent-error" class="text-sm text-red-700">{{ $message }}</p>@enderror
@error('contact_website')<p class="text-sm text-red-700">Richiesta non valida. Riprova.</p>@enderror
<x-button class="w-full" type="submit">Invia richiesta</x-button>
</form></x-guest-layout>
