<x-layouts.retailer title="Giacenza"><h1 class="mb-4 break-words">{{ $item->name }}</h1><x-inventory-status :item="$item" />
@if(session('status'))<x-alert class="mt-4" variant="success">{{ session('status') }}</x-alert>@endif
@if($item->proposed_data)<x-alert class="mt-4" title="Modifica in verifica">I dati qui sotto sono quelli approvati. La proposta sarà applicata dopo verifica amministrativa.</x-alert>@endif
@if($item->rejection_reason)<x-alert class="mt-4" variant="danger">{{ $item->rejection_reason }}</x-alert>@endif
<x-card class="my-5"><p>{{ $item->brand }} · {{ $item->category }} · {{ $item->province }}</p><p class="mt-3">Quantità: {{ $item->quantity }} · Prezzo: {{ \App\Support\DisplayMoney::euros($item->zero_price_cents) }}</p><dl class="mt-3 grid gap-2 sm:grid-cols-2"><div><dt>Codice / EAN</dt><dd>{{ $item->sku ?: '—' }} / {{ $item->ean ?: '—' }}</dd></div><div><dt>Condizione</dt><dd>{{ match($item->condition->value){'new'=>'Nuovo','end_of_line'=>'Fine serie','old_stock'=>'Fondo magazzino',default=>'Imballo danneggiato'} }}</dd></div><div><dt>Consegna</dt><dd>{{ $item->pickup_available ? 'Ritiro in sede':'' }} {{ $item->shipping_available ? 'Spedizione':'' }}</dd></div><div><dt>Scambio</dt><dd>{{ $item->exchange_available ? 'Disponibile':'Non disponibile' }}</dd></div>@if($item->list_price_cents!==null)<div><dt>Prezzo di listino</dt><dd>{{ \App\Support\DisplayMoney::euros($item->list_price_cents) }}</dd></div>@endif</dl><p class="mt-3 whitespace-pre-wrap break-words">{{ $item->description }}</p><div class="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">@foreach($item->images as $photo)<img loading="lazy" decoding="async" class="aspect-square w-full rounded-xl object-cover" src="{{ route('inventory.image',[$item,$photo->position]) }}" alt="{{ $item->name }}">@endforeach</div></x-card>
<x-inventory-actions :item="$item" />
@if($item->published_at && in_array($item->status->value,['published','change_pending']))<x-button class="mt-4" variant="secondary" :href="route('availability.create',$item)">Apri form pubblico Richiedi giacenza</x-button>@endif
@if($item->proposed_data)<x-card class="mt-5"><h2>Proposta in verifica</h2><p class="mt-2">{{ $item->proposed_data['name'] }} · {{ \App\Support\DisplayMoney::euros($item->proposed_data['zero_price_cents']) }}</p><p class="break-words">{{ $item->proposed_data['description'] }}</p><div class="mt-4 grid grid-cols-2 gap-3">@foreach($item->proposed_images??[] as $position=>$photo)<img loading="lazy" decoding="async" class="aspect-square w-full rounded-xl object-cover" src="{{ route('inventory.image',[$item,$position,'proposed'=>1]) }}" alt="Foto proposta">@endforeach</div></x-card>@endif
</x-layouts.retailer>
