<x-layouts.retailer title="Credito maturato">
<h1>Credito maturato</h1><p class="mt-2 text-slate-600">Vendite, rimborsi e bonifici in EUR. La commissione di ciascuna vendita resta quella registrata al momento della vendita.</p>
@if(session('status'))<x-alert class="mt-4" title="Operazione completata"><p>{{ session('status') }}</p></x-alert>@endif
@if($errors->any())<x-alert class="mt-4" variant="danger" title="Richiesta non completata">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</x-alert>@endif
<div class="mt-6 grid min-w-0 gap-4 sm:grid-cols-2 xl:grid-cols-4">
@foreach(['Credito disponibile'=>\App\Support\DisplayMoney::euros($available),'Totale netto maturato'=>\App\Support\DisplayMoney::euros($earned),'Bonifici in attesa'=>\App\Support\DisplayMoney::euros($reserved),'Commissione piano'=>$plan ? \App\Support\DisplayMoney::percent($plan->commission_basis_points) : 'Nessun piano attivo'] as $label=>$value)
<x-card><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-2 break-words text-xl font-semibold">{{ $value }}</p></x-card>@endforeach
</div>
<x-card class="mt-6"><h2>Ricevi il credito</h2><p class="mt-2">La richiesta comprende tutto il credito disponibile. La banca dispone il pagamento esternamente al gestionale.</p>
@if(!$retailer->iban)<p class="mt-3"><a class="underline" href="{{ route('retailer.profile') }}">Inserisci un IBAN valido nel profilo</a> prima di richiedere il bonifico.</p>@else<p class="mt-3 text-sm">IBAN: •••• {{ substr($retailer->iban,-4) }}</p>@endif
<form method="POST" action="{{ route('retailer.credit.payout') }}" class="mt-4">@csrf<x-button type="submit" :disabled="$pending || $available <= 0 || !$retailer->iban">RICEVI IL BONIFICO</x-button></form>
@if($pending)<p class="mt-3">Hai già un bonifico in attesa di verifica.</p>@endif
<p class="mt-4 text-sm text-slate-600"><strong>Tienili per acquistare prodotti:</strong> puoi lasciare il credito sul conto. L’utilizzo del credito al checkout non è ancora disponibile.</p></x-card>
<section class="mt-8" aria-labelledby="sales-heading"><h2 id="sales-heading">Storico vendite</h2><div class="mt-4 grid min-w-0 gap-4 lg:grid-cols-2">
@forelse($sales as $line)<x-card><h3 class="break-words font-semibold">{{ $line->name }}</h3><p class="break-all text-sm text-slate-500">{{ $line->sale->ordered_at->format('d/m/Y H:i') }} · Ordine {{ $line->sale->external_order_id }}</p>
<dl class="mt-3 grid grid-cols-2 gap-3 text-sm">@foreach(['Quantità'=>$line->quantity,'Prezzo unitario'=>\App\Support\DisplayMoney::euros($line->unit_price_cents),'Sconto'=>\App\Support\DisplayMoney::euros($line->discount_cents),'Lordo'=>\App\Support\DisplayMoney::euros($line->line_total_cents),'Commissione'=>\App\Support\DisplayMoney::percent($line->commission_basis_points).' · '.\App\Support\DisplayMoney::euros($line->commission_cents),'Netto'=>\App\Support\DisplayMoney::euros($line->net_cents ?? $line->line_total_cents-$line->commission_cents)] as $label=>$value)<div><dt class="text-slate-500">{{ $label }}</dt><dd class="break-words">{{ $value }}</dd></div>@endforeach</dl><x-badge class="mt-3">{{ match($line->sale->status->value) {'paid'=>'Pagata','refunded'=>'Rimborsata','partially_refunded'=>'Rimborso parziale',default=>'In attesa'} }}</x-badge></x-card>
@empty<x-empty-state title="Nessuna vendita" description="Le vendite confermate compariranno qui." />@endforelse</div><div class="mt-4">{{ $sales->links() }}</div></section>
<section class="mt-8" aria-labelledby="movements-heading"><h2 id="movements-heading">Storico movimenti</h2><div class="mt-4 space-y-3">@forelse($movements as $movement)<x-card><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="font-semibold">{{ $movement->description ?? $movement->type->value }}</p><p class="text-sm text-slate-500">{{ $movement->created_at->format('d/m/Y H:i') }}</p></div><p class="font-semibold">{{ \App\Support\DisplayMoney::euros($movement->amount_cents) }}</p></div>@if(!$movement->available_at || $movement->available_at > now())<x-badge>Non ancora disponibile</x-badge>@endif</x-card>@empty<x-empty-state title="Nessun movimento" description="Il saldo è sempre ricostruibile dai movimenti." />@endforelse</div><div class="mt-4">{{ $movements->links() }}</div></section>
<section class="mt-8" aria-labelledby="payouts-heading"><h2 id="payouts-heading">Storico bonifici</h2><div class="mt-4 space-y-3">@forelse($payouts as $payout)<x-card><p class="font-semibold">{{ \App\Support\DisplayMoney::euros($payout->amount_cents) }}</p><p class="text-sm">{{ $payout->created_at->format('d/m/Y H:i') }} · IBAN •••• {{ substr($payout->iban ?? '',-4) }}</p><x-badge>{{ match($payout->status->value){'pending'=>'In attesa','paid'=>'Pagato','rejected'=>'Rifiutato'} }}</x-badge>@if($payout->rejection_reason)<p class="mt-2">{{ $payout->rejection_reason }}</p>@endif</x-card>@empty<x-empty-state title="Nessun bonifico" description="Le richieste di pagamento compariranno qui." />@endforelse</div><div class="mt-4">{{ $payouts->links() }}</div></section>
</x-layouts.retailer>
